//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MP819xVC.rc 使用
//
#define IDC_START                       3
#define IDC_WRITE_MAC                   4
#define IDC_WRITE_EEPROM                7
#define IDC_READ_EEPROM                 8
#define IDC_READ_TX_POWER               9
#define IDC_READ_MAC_ADDR               10
#define IDC_READ_EE_TX_POWER            11
#define IDC_WRITE_EE_TX_POWER           12
#define IDC_REG_READ                    14
#define IDC_REG_WRITE                   15
#define IDM_ABOUTBOX                    0x0010
#define IDC_RF_REG_READ                 16
#define IDC_RF_REG_WRITE                17
#define IDC_RF_Thermal_READ             18
#define IDC_UPDATE_EFUSE                19
#define IDC_Thermal_READ                20
#define IDC_TSSI_READ                   21
#define IDC_KFREE                       21
#define IDC_RX_ALL_ENABLE               22
#define IDC_MONITOR                     23
#define IDC_RX_FILTER                   24
#define IDC_SET_DEST_MAC                25
#define IDC_DbgFieldBtn                 26
#define IDC_LED1_CONTROL                27
#define IDC_BT                          29
#define IDC_LED1_CONTROL3               30
#define IDC_BT_PIN_GET                  30
#define IDC_CUSTOMER_SEL_COM            31
#define IDC_SYSON_REG_READ              32
#define IDC_SYSON_REG_WRITE             33
#define IDC_BT_PIN_SET                  34
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MP819xVC_DIALOG             102
#define IDS_ABOUT_REALTEK               102
#define IDS_MP819xVC                    103
#define IDS_VERSION                     104
#define IDD_DEV_PANEL                   107
#define IDD_TAB_ADCSAMPLE               108
#define IDD_TAB_REGDUMP                 109
#define IDD_INFODLG                     110
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDI_REALTEK_ICO                 135
#define IDB_BITMAP2                     139
#define IDB_BITMAP1                     142
#define IDD_FLASH_DLG                   145
#define IDC_PREAMBLE                    149
#define IDC_CHANNEL                     150
#define IDC_ANTENNA                     151
#define IDC_ANTENNA_TX                  151
#define IDC_RATE                        152
#define IDC_TEST_LIST                   153
#define IDC_TX_POWER                    154
#define IDC_ANTENNA_RX                  155
#define IDC_TX_POWER2                   156
#define IDC_TxSC_Selection              157
#define IDC_PKTLEN                      158
#define IDC_TX_POWER3                   158
#define IDC_PATTERN                     159
#define IDC_RESULT                      160
#define IDC_SELF_MAC_ADDR               161
#define IDC_CIS_DATA                    162
#define IDC_PHY_RX_COUNTER              163
#define IDC_PHY_RX_COUNTER_OK           163
#define IDC_TX_COUNT                    164
#define IDC_MAC_ADDRESS                 165
#define IDC_PacketLength                165
#define IDC_PKT_GROUP                   166
#define IDC_PacketLength2               166
#define IDC_PHY_RX_COUNTER_ERR          166
#define IDC_GROUP_DELAY                 167
#define IDC_PacketLength3               167
#define IDC_TX_POWER4                   167
#define IDC_EEPROM_TYPE                 168
#define IDC_EE_BYTE_OFFSET              169
#define IDC_EE_BYTE_VALUE               170
#define IDC_MODULATION                  171
#define IDC_REG_OFFSET                  172
#define IDC_DEST_MAC_ADDR               173
#define IDC_REG_DATA                    174
#define IDC_INITIAL_GAIN                175
#define IDC_Xtal_XinXout                176
#define IDC_TX_PMAC_PERIOD              177
#define IDC_RFCHIP                      178
#define IDC_CHANNEL_WIDTH               179
#define IDC_RFREG_RFPATH                180
#define IDC_ANT_OFFSET_D                181
#define IDC_CrystalCap                  182
#define IDC_EFUSE_UTILIZE               183
#define IDC_RF_TYPE_AUTOLOAD            184
#define IDC_TXCHARGE_PUMP               185
#define IDC_ANT_OFFSET_B                186
#define IDC_ANT_OFFSET_C                187
#define IDC_CUSTOMER_SEL_PWR            188
#define IDC_CUSTOMER_SEL_PWR_LMT        189
#define IDC_MAC_RX_COUNTER_OK           190
#define IDC_MAC_RX_COUNTER_ERR          191
#define IDC_TX_PMAC_TYPE                192
#define IDC_RF_PATH_SETTING             193
#define IDC_RF_PATH_SETTING_DUPLICATE   194
#define IDC_QUIT                        1001
#define IDC_RESET                       1002
#define IDC_HLP                         1003
#define IDC_ENABLE_AUTOINSTALL          1004
#define IDC_PREAMBLE_STATIC             1005
#define IDC_ANTENNA_STATIC              1006
#define IDC_RF_PATH_STATIC              1006
#define IDC_ANTENNA_TX_STATIC           1006
#define IDC_MODULATION_STATIC           1007
#define IDC_ABOUT_VERSION               1008
#define IDC_CHANNEL_WIDTH_STATIC        1008
#define IDC_STATIC_GAIN                 1009
#define IDC_File_Index                  1010
#define IDC_ANTENNA_RX_STATIC           1011
#define IDC_ANT_OFFSET_STATIC           1012
#define IDC_STATIC_Xtal_XinXout         1012
#define IDC_STATIC_CrystalCap           1013
#define IDC_STATIC_AUTO_TEST            1014
#define IDC_STATIC_MISCELLANEOUS        1015
#define IDC_STATIC_AntennaOffsetB       1016
#define IDC_STATIC_Xtal                 1016
#define IDC_STATIC_AntennaOffsetC       1017
#define IDC_STATIC_RFATxPower           1017
#define IDC_STATIC_BTPin                1017
#define IDC_STATIC_AntennaOffsetD       1018
#define IDC_STATIC_EfuseUsed            1019
#define IDC_RFPathSwitch                1020
#define IDC_LIST1                       1021
#define IDC_BUTTON_IQK                  1021
#define IDC_BT_WIFI                     1022
#define IDC_BT_PORT_NO_TEXT             1023
#define IDC_BT_RATE_TEXT                1024
#define IDC_BT_PORT_NUMBER              1025
#define IDC_BT_RATE                     1026
#define IDC_BUTTON_DIG                  1027
#define IDC_BUTTON_DPK                  1028
#define IDC_BUTTON_U2U3_SWITCH          1029
#define IDC_BUTTON_DIG2                 1030
#define IDC_BUTTON_LCK                  1030
#define IDC_BUTTON_CFO_TRACK            1031
#define IDC_BT_PIN_VALUE                1031
#define IDC_COMBO4                      1032
#define IDC_STATIC_REG_MONITOR_1        1033
#define IDC_STBC                        1034
#define IDC_LDPC                        1035
#define IDC_XMIT_OK                     1036
#define IDC_RCV_OK                      1037
#define IDC_ACK_PKT_COUNTER             1038
#define IDC_RCV_ERR                     1039
#define IDC_REG_MONITOR_1               1040
#define IDC_KFREE_VALUE                 1041
#define IDC_CUSTOM1                     1044
#define IDC_CHECK1                      1046
#define IDC_CHECK_ENABLE_TX_PWR_LMT     1046
#define IDC_BUTTON_DEVBB                1047
#define IDC_PWR_INDEX_FROM_EFUSE        1048
#define IDC_BUTTON_ACK_COUNTER_EN       1049
#define IDC_DEV_TEXT_FIELD              1050
#define IDC_DEV_ADCSMP_BTN              1051
#define IDC_DEV_TRIG_TIME               1053
#define IDC_DEV_TRIGSIG_SEL             1054
#define IDC_DEV_DMADATA_SEL             1055
#define IDC_DEV_POLL_TIME               1056
#define IDC_TRIG_HINT                   1058
#define IDC_TRIG_HINT2                  1059
#define IDC_TRIG_HINT3                  1060
#define IDC_TRIG_HINT4                  1061
#define IDC_DEV_MAC_TRIG                1062
#define IDC_DEV_BB_TRIG                 1063
#define IDC_BB_TAB_FRAME                1064
#define IDC_TAB_ADCSTATUS2              1065
#define IDC_TAB_ADCSTATUS1              1066
#define IDC_TX_PMAC_MODE_BTN            1067
#define IDC_TX_PMAC_PERIOD_LABEL        1068
#define IDC_TX_PKT_SETTING              1069
#define IDC_TX_PMAC_TYPE_LABEL          1070
#define IDC_TxSubCarrier_STATIC         1071
#define IDC_STATIC_ACK_PKT_COUNTER      1072
#define IDC_TxSC_Help_Btn               1073
#define IDC_INFO_TEXTBOX                1074
#define IDC_TX_POWER_B_LABEL            1075
#define IDC_TX_POWER_D_LABEL            1076
#define IDC_TX_POWER_C_LABEL            1077
#define IDC_TX_POWER_A_LABEL            1078
#define IDC_ADC_SAVE_FILE_LOCATION      1079
#define IDC_ADC_SAVE_FILE_BTN           1080
#define IDC_RF_PATH_SETTING_STATIC      1081
#define IDC_RXFILTER_BTN                1082
#define IDC_RFE_TYPE_TEXT               1083
#define IDC_FLASH                       1084
#define IDC_RF_PATH_SETTING_STATIC_DUPLICATE 1085
#define IDC_FLASH_DOWNLOAD              1086
#define IDC_FLASH_VERIFY                1087
#define IDC_IMAGE_FILE_PATH             1088
#define IDC_STATIC_IMAGE_FILE_PATH      1089
#define IDC_IMAGE_FILE_BROWSE           1090
#define IDC_STATIC_FLASH_DL_ADDR        1092
#define IDC_STATIC_FW                   1092
#define IDC_FLASH_DL_START_ADDR         1093
#define IDC_FW_TYPE                     1093
#define IDC_STATIC_ERASE_START_ADDR     1094
#define IDC_ERASE_START_ADDR            1095
#define IDC_STATIC_ERASE_LENGTH         1096
#define IDC_ERASE_LENGTH                1097
#define IDC_FALSH_ERASE                 1098
#define IDC_STATIC_ERASE_UNIT           1099
#define IDC_AUTOINSTALL_STATUS          1100
#define IDC_STATIC_FLASH_ERASE          1100
#define IDC_STATIC_STATUS               1101
#define IDC_FLASH_STATUS                1102
#define IDC_ERASE_LENGTH_CHECK_HEX      1103
#define IDC_FLASH_PROGRESS              1104
#define IDC_ERASE_ALL                   1105
#define IDC_ERASE_ISO                   1106
#define IDC_ERASE_USER_MODE             1107
#define IDC_STATIC_FLASH_DOWNLOAD       1108
#define AboutQUIT                       1109
#define AboutEdit                       1113
#define IDC_Recover                     1114
#define ID_Save                         1115
#define IDC_Restore                     1126
#define Power1                          1128
#define Power2                          1129
#define Power3                          1130
#define Power4                          1131
#define Power5                          1132
#define Power6                          1133
#define Power7                          1134
#define Power8                          1135
#define Power9                          1136
#define Power10                         1137
#define Power11                         1138
#define Power12                         1139
#define Power13                         1140
#define Power14                         1141
#define ID_Exit                         1142
#define Power26                         1143
#define Power28                         1144
#define Power30                         1145
#define Power32                         1146
#define Power34                         1147
#define Power36                         1148
#define Power38                         1149
#define Power40                         1150
#define Power42                         1151
#define Power44                         1152
#define Power46                         1153
#define Power48                         1154
#define Power50                         1155
#define Power52                         1156
#define Power54                         1157
#define Power56                         1158
#define Power58                         1159
#define Power60                         1160
#define Power62                         1161
#define Power64                         1162
#define Power66                         1163
#define Power68                         1164
#define Power70                         1165
#define Power72                         1166
#define Power74                         1167
#define Power76                         1168
#define Power78                         1169
#define Power80                         1170
#define Power82                         1171
#define Power84                         1172
#define Power86                         1173
#define Power100                        1174
#define Power104                        1175
#define Power108                        1176
#define Power112                        1177
#define Power116                        1178
#define Power120                        1179
#define Power124                        1180
#define Power128                        1181
#define Power132                        1182
#define Power136                        1183
#define Power140                        1184
#define Power149                        1185
#define Power153                        1186
#define Power157                        1187
#define Power161                        1188
#define Power1g                         1189
#define Power2g                         1190
#define Power3g                         1191
#define Power4g                         1192
#define Power5g                         1193
#define Power6g                         1194
#define Power7g                         1195
#define Power8g                         1196
#define Power9g                         1197
#define Power10g                        1198
#define Power11g                        1199
#define Power12g                        1200
#define Power13g                        1201
#define Power14g                        1202
#define IDC_EFUSE_TARGET_SEL            1500
#define IDC_CHECK_PHY_OK                1501
#define IDC_CHECK_PHY_ERR               1502
#define IDC_CHECK_MAC_OK                1503
#define IDC_CHECK_MAC_ERR               1504
#define IDC_Enhance_AntiInterference    1505
#define IDC_STATIC_RSSI_MONITOR         1506
#define IDC_STATIC_RSSI_VALUE           1507
#define IDC_EDIT1                       1508
#define IDC_BUTTON1                     1509
#define IDC_RDT_MEMO1                   1510
#define IDC_BTN_STARTVSA                1511
#define IDC_EDT_IP                      1512
#define IDC_BTN_CON                     1513
#define IDC_BUTTON2                     1514
#define IDC_BTN_VSG                     1514

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1515
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
